ENCODER_MAP_ENABLE = yes
OS_DETECTION_ENABLE = yes
RAW_ENABLE = yes
USER_NAME = halcyon_modules
OBBUT_SWIFT_FIRMWARE_MODULE = EloraFirmware
OBBUT_SWIFT_FIRMWARE_DEFINE = OBBUT_FIRMWARE_ELORA
include $(QMK_USERSPACE)/users/obbut_halcyon/rules.mk
