# ZSA QMK Firmware build environment
# Uses ZSA's fork which includes Planck EZ, Moonlander, etc.

FROM swift:6.3.3-noble AS swift-toolchain

RUN cp -L /usr/lib/*/libncurses.so.6 /tmp/libncurses.so.6

FROM ghcr.io/qmk/qmk_cli

COPY --from=swift-toolchain /usr/bin/swift-driver /usr/bin/swift-driver
COPY --from=swift-toolchain /usr/bin/swift-frontend /usr/bin/swift-frontend
COPY --from=swift-toolchain /usr/bin/clang-21 /usr/bin/clang-21
COPY --from=swift-toolchain /usr/lib/swift /usr/lib/swift
COPY --from=swift-toolchain /usr/lib/clang/21 /usr/lib/clang/21
COPY --from=swift-toolchain /tmp/libncurses.so.6 /usr/local/lib/libncurses.so.6
RUN ldconfig \
    && ln -s swift-driver /usr/bin/swift \
    && ln -s swift-driver /usr/bin/swiftc \
    && ln -s clang-21 /usr/bin/clang \
    && ln -s swift-frontend /usr/bin/swift-autolink-extract \
    && swift --version

# Clone ZSA's QMK fork (shallow clone to save space)
RUN git clone --depth 1 https://github.com/zsa/qmk_firmware.git /qmk_firmware

# Initialize submodules needed for the build
WORKDIR /qmk_firmware
RUN make git-submodule

# Set up for userspace overlay
ENV QMK_USERSPACE=/qmk_userspace

WORKDIR /qmk_firmware
