// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_RGB_PREVIEW
#define RGB_MATRIX_TIMEOUT 300000
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 5
#define AUTO_MOUSE_TIME 650
#define AUTO_MOUSE_DELAY 200
#define AUTO_MOUSE_DEBOUNCE 25
#define AUTO_MOUSE_THRESHOLD 10
