ENCODER_MAP_ENABLE = yes
RAW_ENABLE = yes
OPT_DEFS += -DOBBUT_KEYCHRON_FIRMWARE
OBBUT_SWIFT_FIRMWARE_MODULE = Q15Firmware
OBBUT_SWIFT_FIRMWARE_DEFINE = OBBUT_FIRMWARE_Q15
include $(QMK_USERSPACE)/users/obbut_keymap/rules.mk
